CREATE TABLE TB_USER_AUTHORITY
(
    USERNAME  VARCHAR(50) NOT NULL,
    AUTHORITY VARCHAR(50) NOT NULL,
    CONSTRAINT PK_USER_AUTHORITY PRIMARY KEY (USERNAME, AUTHORITY)
#     CONSTRAINT FK_USERNAME FOREIGN KEY (USERNAME) REFERENCES USER (USERNAME)
#         ON UPDATE CASCADE
#         ON DELETE CASCADE,
#     CONSTRAINT FK_AUTHORITY FOREIGN KEY (AUTHORITY) REFERENCES AUTHORITY (AUTHORITY)
#         ON UPDATE CASCADE
#         ON DELETE CASCADE
)